# Generated by Django 2.0.4 on 2018-04-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('website', models.URLField()),
                ('state', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=256)),
                ('postal_code', models.IntegerField()),
                ('address_1', models.TextField()),
                ('address_2', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Products_and_Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('sac', models.IntegerField()),
                ('Taxes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=256)),
                ('supplier_name', models.CharField(max_length=256)),
                ('pan_number', models.IntegerField()),
                ('mobile_number', models.IntegerField()),
                ('address', models.TextField()),
                ('no_own_vehicles', models.IntegerField(default=1)),
                ('alternate_number', models.IntegerField(default=models.IntegerField())),
                ('service_origin', models.TextField()),
                ('service_destination', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Taxes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_name', models.TextField()),
                ('abbrevation', models.TextField()),
                ('tax_rate', models.IntegerField()),
            ],
        ),
    ]
