# Generated by Django 2.0.4 on 2018-04-21 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Logistical', '0004_auto_20180421_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('invoice_date', models.DateField()),
                ('payment_due', models.DateField()),
                ('service_origin', models.CharField(max_length=512)),
                ('service_destination', models.CharField(max_length=512)),
                ('truck_number', models.TextField()),
                ('truck_type', models.TextField()),
                ('driver_name', models.CharField(max_length=256)),
                ('driver_number', models.IntegerField()),
                ('advance_money', models.IntegerField()),
                ('balance_money', models.IntegerField()),
                ('mobile_number', models.IntegerField()),
                ('description', models.TextField()),
                ('service_fee', models.IntegerField()),
                ('taxes', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('total', models.IntegerField()),
                ('total_in_words', models.TextField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Logistical.Customers')),
                ('name_supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_supplier', to='Logistical.Suppliers')),
                ('number_supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='number_supplier', to='Logistical.Suppliers')),
                ('pan_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panNumber', to='Logistical.Suppliers')),
                ('sac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saca', to='Logistical.Products_and_Services')),
            ],
        ),
    ]
