# Generated by Django 2.0.4 on 2018-05-07 17:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logistical', '0005_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='invoice_date',
            field=models.DateField(default=datetime.datetime(2018, 5, 7, 17, 54, 9, 977341)),
        ),
    ]
