# Generated by Django 2.0.4 on 2018-05-08 17:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Logistical', '0006_auto_20180507_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='name',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='number_supplier',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='pan_number',
        ),
        migrations.AlterField(
            model_name='orders',
            name='advance_money',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orders',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orders',
            name='invoice_date',
            field=models.DateField(default=datetime.datetime(2018, 5, 8, 17, 32, 2, 8377)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='payment_due',
            field=models.DateField(default=datetime.datetime(2018, 5, 8, 17, 32, 2, 8405)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='service_fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orders',
            name='taxes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Logistical.Taxes'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='truck_number',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='orders',
            name='truck_type',
            field=models.CharField(max_length=512),
        ),
    ]
