# Generated by Django 2.0.4 on 2018-05-16 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logistical', '0013_auto_20180516_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='cgst',
            field=models.IntegerField(choices=[(1, 2.5), (2, 6), (3, 8.5), (4, 14)], default=1),
        ),
        migrations.AddField(
            model_name='orders',
            name='sgst',
            field=models.IntegerField(choices=[(1, 2.5), (2, 6), (3, 8.5), (4, 14)], default=1),
        ),
        migrations.AlterField(
            model_name='orders',
            name='invoice_date',
            field=models.DateField(default=datetime.datetime(2018, 5, 16, 13, 23, 33, 979569)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='payment_due',
            field=models.DateField(default=datetime.datetime(2018, 5, 16, 13, 23, 33, 979596)),
        ),
        migrations.AlterField(
            model_name='pod',
            name='loading_date',
            field=models.DateField(default=datetime.datetime(2018, 5, 16, 13, 23, 33, 980661)),
        ),
        migrations.AlterField(
            model_name='pod',
            name='payment_date',
            field=models.DateField(default=datetime.datetime(2018, 5, 16, 13, 23, 33, 980772)),
        ),
        migrations.AlterField(
            model_name='pod',
            name='pod_receiving_date',
            field=models.DateField(default=datetime.datetime(2018, 5, 16, 13, 23, 33, 980635)),
        ),
    ]
