# Generated by Django 2.0.4 on 2018-04-21 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Logistical', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
