# Generated by Django 2.0.4 on 2018-04-21 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Logistical', '0003_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
