# Generated by Django 2.0.4 on 2018-05-19 12:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logistical', '0014_auto_20180516_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='invoice_date',
            field=models.DateField(default=datetime.datetime(2018, 5, 19, 12, 41, 59, 543829)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='payment_due',
            field=models.DateField(default=datetime.datetime(2018, 5, 19, 12, 41, 59, 543855)),
        ),
        migrations.AlterField(
            model_name='pod',
            name='loading_date',
            field=models.DateField(default=datetime.datetime(2018, 5, 19, 12, 41, 59, 545073)),
        ),
        migrations.AlterField(
            model_name='pod',
            name='payment_date',
            field=models.DateField(default=datetime.datetime(2018, 5, 19, 12, 41, 59, 545277)),
        ),
        migrations.AlterField(
            model_name='pod',
            name='pod_receiving_date',
            field=models.DateField(default=datetime.datetime(2018, 5, 19, 12, 41, 59, 545043)),
        ),
    ]
